# Generated by Django 5.2.5 on 2025-08-13 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='distance_km',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='predicted_duration',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
