# Generated by Django 5.2.5 on 2025-08-13 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_shipment_distance_km_shipment_predicted_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='maintenance_cost',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='total_km_driven',
            field=models.FloatField(default=0),
        ),
    ]
