# Generated by Django 5.2.5 on 2025-08-14 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='weather_forecast',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
